### ISSUE TITLE
Добавить .gitignore

### ISSUE THREAD

**Issue by aporlov** [pomasql/poma#5]
Добавить .gitignore

**Comment by LeKovr** [comment]
Пустой?

**Comment by aporlov** [comment]
Добавил файл

**Comment by LeKovr** [comment]
Содержимое каталога poma будет в проектах (как и показано в poma-sample) лежать в папке sql/poma, в которую вообще никто заходить не будет, ибо незачем. Т.о., в poma не будет .env и .build
